### ISSUE TITLE
Galasa-dev docs to instruct ecosystem install to use Helm chart method instead of docker operator method.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/galasa.dev#540]
## Story
As a tester trying to set up a  galasa ecosystem to use for running tests, Given I have a namespace allocated on a kube cluster, I want to follow instructions on how to deploy Galasa to the cluster using a helm chart, so I can deploy Replace  'how to install an ecosystem using the kube operator' with installing instructions for using a helm chart instead. 

## Background
This brings our documentation more in-line with dropping support for the existing kube operator, as it's not OLM-based. When we have an OLM-based operator we can re-work these instructions to include that in addition to the helm-install method.

## Tasks
- [x] Remove the install instructions about the kube operator from galasa-dev
- [x] Write a new section about installing the kube ecosystem using helm and the helm chart.
- [x] Mike C or Eamon to review
- [ ] Close when published.

**Comment by CaroMac** [comment]
PR is here https://github.com/galasa-dev/galasa.dev/pull/579
Preview is here 
Assigned to Eamonn for initial review
Yet to remove the docker instructions but will do so

**Comment by CaroMac** [comment]
docker instructions removed, updates made.

**Comment by CaroMac** [comment]
[ ] Awaiting removal of the Tekton check from the Galasa site. It prevents the merge queue from being used.
