### ISSUE TITLE
Document the `galasactl project create` function

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/galasa.dev#548]
Draft information is here: https://ibm.box.com/s/mz154y5e5q9a0k86zw619cfyfxmtj9of 

Syntax reference information is here: https://github.com/galasa-dev/cli/blob/main/docs/generated/galasactl.md

## Tasks
- [ ] Check that builds are working again.
- [ ] Get approval from anyone
- [ ] Publish and close.

**Comment by techcobweb** [comment]
Moving this to active as @caromac is working on it now.

**Comment by CaroMac** [comment]
this is complete and reviewed by Mike but not yet published.

**Comment by techcobweb** [comment]
What's stopping this being published now then ? The function is in 0.25.0 so going public should be OK...

**Comment by CaroMac** [comment]
[ ] Awaiting removal of the Tekton check from the Galasa site. It prevents the merge queue from being used.
