### ISSUE TITLE
Github workflow Technical Debt

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/galasa.dev#581]
## Story
As a galasa developer, I want to use one copy of the deploy step (i.e. Deploy-dotdev and deploy-vnext are duplicate functions), so that I can maintain and update the code base easily and monitor issues with the deployment in the vnext instance before it reaches deployment date.

## Tasks
- [ ] Identify why the matrix is not being parsed on as an output from one function to another and we are 
- [ ] Create a new function to generate the matrix
- - [ ] If branch == main : Steps fork to create the production site matrix will need to include all 3 sites of galasa.dev
- - [ ] if branch  == next : Steps fork to create the vnext site matrix which will need to include the eu-gb-next site
- [ ] Create a new single dpeloyment function that woulod use the resulting matrix from the above function

**Comment by techcobweb** [comment]
Which artifacts are you referring to above @KirbyKatcher ? A few more details in the background might give more context on what's not currently working when you tried it, and what needs changing and why ?

**Comment by abhinavraajput** [comment]
@techcobweb assign me this
